server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://10.0.0.17:3306/all?useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
